### PR TITLE
Corrected linker script include for locm3

### PR DESCRIPTION
**Pull request by Annath**
Fixes the linker script to include the correct file (`cortex-m-generic.ld` instead of `libopencm3_stm32f4.ld`), which fixes broken builds with the current version of libopencm3.

### CODE REVIEW

**Comment by esden** [comment]
Thank you for this. But should we not also update the locm3 submodule at the same time? The submodule is pinned to a release that works with the examples, so if we update the linker script handling locm3 has to be updated too.

**Comment by Annath** [comment]
Maybe I did something wrong, but it seems that locm3 is already pointing to a version that requires this change. I cloned the repo, ran `git submodule init && git submodule update`, attempted to run `make`, and got the following error:

```
ld: cannot open linker script file libopencm3_stm32f4.ld: No such file or directory
```

This is on the head of master. The version of locm3 that was pulled by `git submodule update` isn't generating `libopencm3_stm32f4.ld`.

Have I missed a step?

**Comment by amaciuszonek** [comment]
I can confirm, that following the README for the examples does pull the locm3 and reproduce the issue as well.

**Comment by esden** [comment]
Thank you for this contribution. Sorry it took so long for me to get to it.

I have confirmed that the linker script change needs to be done.

The problem with using gdb-multiarch is that it is only available on some specific platforms not everywhere.

**Comment by esden** [comment]
I have cherry picked the patch fixing the linker script from you. Again, thank you for your contribution. :)

**Pull request closed without merging**
